# Generated by Django 3.1.4 on 2020-12-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_01', models.CharField(default=123, max_length=24, verbose_name='1번 문항')),
                ('survey_02', models.CharField(default=123, max_length=24, verbose_name='2번 문항')),
                ('survey_03', models.CharField(default=123, max_length=24, verbose_name='3번 문항')),
                ('survey_04', models.CharField(default=123, max_length=24, verbose_name='4번 문항')),
                ('survey_05', models.CharField(default=123, max_length=24, verbose_name='5번 문항')),
                ('survey_06', models.CharField(default=123, max_length=24, verbose_name='6번 문항')),
                ('survey_07', models.CharField(default=123, max_length=24, verbose_name='7번 문항')),
            ],
        ),
    ]
